# Generated by Django 3.0.7 on 2021-05-26 11:55

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20210526_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Tag')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=75, verbose_name='Tag'))),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='following',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='post',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.TextField(default='', max_length=500, verbose_name='Title'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=75, verbose_name='Tag')),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
