# Generated by Django 3.0.7 on 2021-05-26 12:02

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20210526_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=75, verbose_name='Category')),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=75, verbose_name='Category'),
        ),
    ]
