# Generated by Django 3.0.7 on 2021-05-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='', max_length=10000, verbose_name='Body'),
        ),
    ]
