# Generated by Django 3.0.7 on 2021-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='post.IpModel'),
        ),
    ]
