# Generated by Django 3.0.7 on 2021-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_ipmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='delete',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
