# Generated by Django 3.0.7 on 2021-06-12 11:17

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_likes_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=djrichtextfield.models.RichTextField(default='', verbose_name='Body'),
        ),
    ]
