# Generated by Django 3.0.7 on 2021-05-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
