# Generated by Django 3.0.7 on 2021-05-30 14:02

import authy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_ipmodel_time'),
        ('authy', '0006_auto_20210526_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=authy.models.user_directory_path, verbose_name='Poster'),
        ),
    ]
